config/routes.rb
Bstest::Application.routes.draw do
  resources :workstations

  get "static_pages/home"
  get "static_pages/contact"
  get "mobile_pages/new"
  get 'menu', to: 'mobile_pages#menu', as: 'menu'
  get 'mobile_login', to: 'mobile_pages#login', as: 'mobile_login'
  get 'finish_job', to: 'mobile_pages#finish', as: 'finish_job'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  resources :jobs
  resources :barcodes

  root :to => "static_pages#index"

  

end

app/models/barcode.rb
class Barcode < ActiveRecord::Base
	belongs_to :job
	belongs_to :workstation
	validates_presence_of :barcode_number
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user
	has_many :barcodes
	validates :user_id, presence: true
	validates_presence_of :details, :barcode
	def self.search(search)
	if search
	    where('details LIKE ?', "%#{search}%")
	  else
	    scoped
	  end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates_uniqueness_of :name
	has_many :jobs
end

app/models/workstation.rb
class Workstation < ActiveRecord::Base
	has_many :barcodes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/barcodes_controller.rb
class BarcodesController < ApplicationController

  def new
    @job = Job.find_by_id(params[:job_id])
    @barcode = @job.barcodes.build 
  end

  def create
    @job = Job.find_by_id(params[:barcode][:job_id])
    @barcode = @job.barcodes.build(barcode_params)
    if @barcode.save
      redirect_to @job
    else
      render 'new'
    end
  end

  def show
  end

  def index
  end

  def edit
  end

  def destroy
    @barcode = Barcode.destroy(params[:id])
    redirect_to jobs_path
  end

  private
    def barcode_params
      params.require(:barcode).permit(:barcode_number)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  helper_method :sort_column, :sort_direction
  def index
    @jobs = Job.all
    #@jobs = Job.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => "5", :page => params[:page])
  end
  def new
    @job = current_user.jobs.build 
  end

  def show
    @job = Job.find(params[:id])
    @barcodes = @job.barcodes
    @assigned_user = User.find_by_id(@job.assign_user)
    @created_by = User.find_by_id(@job.user_id)
  end

  def edit
    @job = Job.find(params[:id])  
  end

  def update
    @job = Job.find(params[:id])  
    if @job.update_attributes(job_params)
      flash[:success] = "Job saved!"
      redirect_to jobs_path
    else
      redirect_to jobs_path
    end
  end

  def create
    @job = current_user.jobs.build(job_params)
    if @job.save
      flash[:success] = "Job created!"
      redirect_to jobs_path
    else
      render 'new'
    end
  end

  def destroy
    @job = Job.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to jobs_path }
      format.js
    end
  end

  private

    def job_params
      params.require(:job).permit(:details,:barcode, :assign_user, :importance, :comments, :status)
    end
    def status_params
      params.require(:job).permit(:status)
    end
  def sort_column
    Job.column_names.include?(params[:sort]) ? params[:sort] : "details"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
end

app/controllers/mobile_pages_controller.rb
class MobilePagesController < ApplicationController
	layout 'mobile'

	def new
		@job = current_user.jobs.build 
	end
	def create
    @job = current_user.jobs.build(job_params)
    if @job.save
      flash[:success] = "Job created!"
      redirect_to finish_job
    else
       redirect_to finish_job
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_name(params[:name])
    if user 
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      redirect_to login_path, notice: "Invalid name or password."
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @jobs = @user.jobs.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: "Successfully signed up."
    else
      render "new"
    end
  end

  private
  	def user_params
  		params.require(:user).permit(:name,:barcode_id,:password,:password_confirmation)
  	end
end

app/controllers/workstations_controller.rb
class WorkstationsController < ApplicationController
  before_action :set_workstation, only: [:show, :edit, :update, :destroy]

  # GET /workstations
  # GET /workstations.json
  def index
    @workstations = Workstation.all
  end

  # GET /workstations/1
  # GET /workstations/1.json
  def show
  end

  # GET /workstations/new
  def new
    @workstation = Workstation.new
  end

  # GET /workstations/1/edit
  def edit
  end

  # POST /workstations
  # POST /workstations.json
  def create
    @workstation = Workstation.new(workstation_params)

    respond_to do |format|
      if @workstation.save
        format.html { redirect_to @workstation, notice: 'Workstation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @workstation }
      else
        format.html { render action: 'new' }
        format.json { render json: @workstation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workstations/1
  # PATCH/PUT /workstations/1.json
  def update
    respond_to do |format|
      if @workstation.update(workstation_params)
        format.html { redirect_to @workstation, notice: 'Workstation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @workstation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workstations/1
  # DELETE /workstations/1.json
  def destroy
    @workstation.destroy
    respond_to do |format|
      format.html { redirect_to workstations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workstation
      @workstation = Workstation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workstation_params
      params.require(:workstation).permit(:name)

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def status_as_string(boolean)
		boolean ? 'Complete' : 'In progress'
	end
	def percentage_true(list)
		@count = 0
		list.each do |job|
			@count = @count + 1 if job.status
		end
		return (@count * 100 / list.count)
	end
	def number_true(list)
		@count = 0
		list.each do |job|
			@count = @count + 1 if job.status
		end
		return @count
	end
	def number_false(list)
		@count = 0
		list.each do |job|
			@count = @count + 1 if !job.status
		end
		return @count
	end
	def sortable(column, title = nil)
	    title ||= column.titleize
	    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
	    link_to title, :sort => column, :direction => direction
	end
end

app/helpers/barcodes_helper.rb
module BarcodesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/mobile_pages_helper.rb
module MobilePagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workstations_helper.rb
module WorkstationsHelper
end

app/views/barcodes/destory.html.erb
<h1>Barcodes#destory</h1>
<p>Find me in app/views/barcodes/destory.html.erb</p>

app/views/barcodes/edit.html.erb
<h1>Barcodes#edit</h1>
<p>Find me in app/views/barcodes/edit.html.erb</p>

app/views/barcodes/index.html.erb
 <div class="container-liquid text">
    <div class="row">
    	<div class="col-xs-1"></div>
      <div class="col-xs-10">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <div class="panel-title mob-title"><i class="fa fa-bar-chart-o"></i> CREATE NEW JOB</div>
          </div>
          <div class="panel-body">
            <div id="morris-chart-area"></div>
          </div>
          
        </div>
      </div>
    </div><!-- /.row -->
</div>



<div class="container-liquid text">
  <div class="row">
  	<div class="col-xs-1">
  	</div>
    <div class="col-xs-10">
    	<a class="btn btn-primary btn-lg btn-block mob-btn-back" href="#">Main Menu</a>
    </div>
    <div class="col-xs-1">
    </div>
  </div>
</div>
<br>
<div class="container-liquid text top-pad">
  <div class="row">
  	<div class="col-xs-1">
  	</div>
    <div class="col-xs-10 mob-title">
    	CREATE NEW JOB
    </div>
    <div class="col-xs-1">
    </div>
  </div>
</div>
<br><br>
<div class="container-liquid text">
  <div class="row">
  	<div class="col-xs-1">
  	</div>
    <div class="col-xs-10">
    	<div class="input-group">
		  <span class="input-group-addon mob-input-field"></span>
		  <input type="text" class="form-control mob-input-field" placeholder="Scan Job ID">
		</div>
    </div>
    <div class="col-xs-1">
    </div>
  </div>
</div>
<br>
<div class="container-liquid text">
  <div class="row">
  	<div class="col-xs-1">
  	</div>
    <div class="col-xs-10">
    	<div class="input-group">
		  <span class="input-group-addon mob-input-field"></span>
		  <input type="text" class="form-control mob-input-field" placeholder="Scan Part ID">
		</div>
    </div>
    <div class="col-xs-1">
    </div>
  </div>
</div>
<br>
<div class="container-liquid text">
  <div class="row">
  	<div class="col-xs-1">
  	</div>
    <div class="col-xs-10">
      <a class="btn btn-primary btn-lg btn-block mob-btn" href="#"><i class="fa fa-sign-out"></i> BEGIN JOB</a>
    </div>
    <div class="col-xs-1">
    </div>
  </div>
</div>
  

app/views/barcodes/new.html.erb
<h1>New Barcode</h1>
<fieldset>
    <legend>Add a part</legend>
<%= simple_form_for(@barcode, html: {class: 'form-horizontal' }) do |f| %>
  <%= f.input :barcode_number %>
  <%= f.association :workstation, collection: Workstation.all(order: 'id'), prompt: "Choose a workstation" %>
  <%= f.hidden_field :job_id, :value => @job.id %>
  <div class="form-actions">
   <%= f.button :submit, :class => "btn btn-primary" %>
   <%= link_to "Cancel", jobs_path, :class => "btn" %>
   <div>
<% end %>

app/views/barcodes/show.html.erb
<h1>Barcodes#show</h1>
<p>Find me in app/views/barcodes/show.html.erb</p>

app/views/jobs/destory.html.erb
<h1>Jobs#destory</h1>
<p>Find me in app/views/jobs/destory.html.erb</p>

app/views/jobs/edit.html.erb
<h1> Edit Job </h1>
<blockquote>
  <p class="lead">Update details</p>
</blockquote>
<%= simple_form_for(@job, html: {class: 'form-horizontal' }) do |f| %>
  <%= f.input :details %>
  <%= f.input :barcode %>
  <%= f.input :comments %>
  <%= f.association :user %>
  <div class="form-actions">
   <%= f.button :submit, :class => "btn btn-primary" %>
   <%= link_to "Cancel", jobs_path, :class => "btn" %>
   <div>
<% end %>

app/views/jobs/index.html.erb
<div class="row-fluid">
  <div class="span12">
      <!-- block -->
      <div class="block">
          <div class="navbar navbar-inner block-header">
              <div class="muted pull-left">Jobs</div>
              <div class="pull-right"><span><%= link_to '<i class="icon-white icon-plus"></i> New Job'.html_safe, new_job_path, :class => "badge badge-info" %></span>
              </div>
          </div>
          <div class="block-content collapse in">
              <table class="table table-striped table-hover display" id="jobs">
                  <thead>
                      <tr>
                          <th></th>
                          <th>Job</th>
                          <th>Barcode</th>
                          <th>Opened</th>
                          <th>Updated</th>
                          <th>Added</th>
                          <th>Status</th>
                          <th>Edit</th>
                      </tr>
                  </thead>
                  <tbody>
                      <tr>
                        <% @jobs.each do |job| %>
                          <td><%= link_to "view", job_path(job), :class => "label label-info" %></td>
                          <td><%= job.details %></td>
                          <td><%= job.barcode %></td>
                          <td><%= job.created_at.localtime.to_formatted_s(:short) %></td>
                          <td><%= job.updated_at.localtime.to_formatted_s(:short) %></td>
                          <td><%= time_ago_in_words(job.created_at) %> ago</td>
                          <td>
                          <% if job.status %>
                            <%= link_to "Complete", edit_job_path(job), :class => "label label-info" %>
                          <% else %>
                           <%= link_to "Incomplete", edit_job_path(job), :class => "label" %>
                          <% end %>
                          </td>
                          <td><%= link_to " ", edit_job_path(job), :class => "badge badge-success fa fa-pencil" %>
                            <%= link_to " ", job, method: :delete, data: { confirm: "Are you sure?" }, :class => "badge badge-important fa fa-trash-o" %>
                          </td>
                      </tr>

                      <% end %>
                  </tbody>
              </table>
          </div>


      </div>
      <!-- /block -->
  </div>
</div>

app/views/jobs/new.html.erb
<h1>New Job</h1>
<fieldset>
    <legend>Create a new job </legend>
<%= simple_form_for(@job, html: {class: 'form-horizontal' }) do |f| %>
  <%= f.input :details, :autofocus => true %>
  <%= f.input :barcode %>
  <%= f.input :comments %>
  <div class="form-actions">
   <%= f.button :submit, :class => "btn btn-primary" %>
   <%= link_to "Cancel", jobs_path, :class => "btn" %>
   <div>
<% end %>

app/views/jobs/show.html.erb
<h1>Overview</h1>
<fieldset>
    <legend><%= @job.details %></legend><%= link_to "+ Add barcode", new_barcode_path(:job_id => @job.id), :class => "btn btn-success" %>
<dl class="dl-horizontal">
  <dt>Added:</dt>
  <dd><%= time_ago_in_words(@job.created_at) %> ago.</dd>
  <dt>Created by:</dt>
  <dd><%= link_to @created_by.name, @created_by %></dd>
  <dt>First logged:</dt>
  <dd><%= @job.created_at.localtime %> EST</dd>
  <dt>Last updated:</dt>
  <dd><%= @job.updated_at.localtime %> EST</dd>
  <dt>Barcode</dt>
  <dd><%= @job.barcode %></dd>
  <dt>Comments</dt>
  <dd><%= @job.comments %></dd>
</dl>
<fieldset><legend>Parts</legend>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Barcode ID</th>
      <th>Added</th>
      <th>Controls</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @barcodes.each do |b| %>
      <td><%= b.barcode_number %></td>
      <td><%= b.created_at.localtime.to_formatted_s(:short) %></td>
      <td><%= link_to "", b, method: :delete, data: { confirm: "Are you sure?" }, :class => "btn btn-danger btn-xs fa fa-trash-o" %></td>
    </tr>
  </tbody>
  <% end %>
</table>

<div class="form-actions">
   <%= link_to "Edit Job", edit_job_path(@job), :class => "btn btn-lg btn-primary" %>
   <%= link_to "Back", jobs_path, :class => "btn" %>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Database</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <% if current_user %>
 <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="brand" href="#">Database</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><%= link_to "Home", root_url %></li>
              <li><%= link_to "Jobs", jobs_path %></li>
              <li><%= link_to "Users", users_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>



     <div class="container-fluid">
            <div class="row-fluid">
                <div class="span2" id="sidebar">
                    <ul class="nav nav-tabs nav-stacked">
                        <li>
                            <a href="#"> Jobs</a>
                        </li>
                        <li>
                            <a href="#"> Barcodes</a>
                        </li>
                        <li>
                            <a href="#"> Users</a>
                        </li>
                        <li>
                            <a href="#"> Charts</a>
                        </li>
                    </ul>
                </div>
                
                <!--/span-->
                <div class="span10" id="content">
                    <div class="row-fluid">
                      
                      <%= yield %>
                    </div>
                  </div>
                </div>
              </div>

<% else %>
<%= yield %>
    <%= link_to "Sign Up", signup_path %> or
    <%= link_to "Log In", login_path %>
   <% end %>
  </body>
</html>

app/views/mobile_pages/finish.html.erb
<h1><center><span id="countdown" class="timer"></span><center></h1>
<script>
var seconds = 1;
function secondPassed() {
    var minutes = Math.round((seconds - 30)/60);
    var remainingSeconds = seconds % 60;
    if (remainingSeconds < 10) {
        remainingSeconds = "0" + remainingSeconds;  
    }
    document.getElementById('countdown').innerHTML = minutes + ":" + remainingSeconds;
    if (seconds == 0) {
        clearInterval(countdownTimer);
        document.getElementById('countdown').innerHTML = "Buzz Buzz";
    } else {
        seconds++;
    }
}
 
var countdownTimer = setInterval('secondPassed()', 1000);
</script>
<br>
<%= link_to 'Finish', menu_path, :class => "btn btn-danger btn-lg btn-block mob-btn-back-full" %>

app/views/mobile_pages/login.html.erb
 <div data-role="page" id="index">
            <div data-theme="b" data-role="header">
                <h1>Index page</h1>
            </div>
            
           <div data-role="controlgroup" data-type="horizontal" id="buttoncontainer">
			<a href="index.html" data-role="button">Yes</a>
			</div>
        </div>    

app/views/mobile_pages/menu.html.erb
    <div data-role="footer">
        <div data-role="navbar">
            <ul>
                <li><a href="#">Summary</a></li>
            </ul>
        </div><!-- /navbar -->
</div><!-- /footer -->


<ul data-role="listview" data-inset="true">
    <li><%= link_to 'Change User', mobile_login_path %>


    </li>
     <li><a href="#">
	<h1>New Job</h1>
	       </a>
    </li>
    <li><a href="#">
    	<h1>Open Jobs</h1>
	       </a>
    </li>
    <li><a href="#">
 	<h1>Update Job</h1>
	       </a>
    </li>
    <li><a href="#">
	<h1>View All</h1>
	       </a>
    </li>
    <li><a href="#">
	<h1>Add User</h1>
	       </a>
    </li>
</ul>


<center><h1> Main Menu <h1></center>
<% if !current_user.nil? %>
<center><h3> Logged in as: <%= current_user.name %> <%= current_user.barcode_id %> <h3></center>
	<%= link_to 'Change User', mobile_login_path, :class => "btn btn-primary btn-lg btn-block mob-btn-back-full" %>
	<%= link_to 'New Job', new_job_path, :class => "btn btn-primary btn-lg btn-block mob-btn-back-full" %>
	<%= link_to 'Update Job', menu_path, :class => "btn btn-primary btn-lg btn-block mob-btn-back-full" %>
	<%= link_to 'View Jobs', menu_path, :class => "btn btn-primary btn-lg btn-block mob-btn-back-full" %>
<% else %>
	<%= link_to 'Login', mobile_login_path, :class => "btn btn-primary btn-lg btn-block mob-btn-back-full" %>
<% end %>

app/views/mobile_pages/new.html.erb
    	<%= link_to 'Main Menu', menu_path, :class => "btn btn-primary btn-lg btn-block mob-btn-back" %>
      <br>
      <%= form_for @job do |f| %>
      <%= f.text_field :barcode, :class => "form-control mob-input-field", :maxLength => "10", :autofocus => "true", :onKeyUp => "return runScript(event)" %>
		
      <br>
      <%= f.submit "Create Job", :class => "btn btn-primary btn-lg btn-block mob-btn"%>
  <% end %>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :barcode_id %><br />
    <%= f.text_field :barcode_id %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/workstations/_form.html.erb
<%= simple_form_for(@workstation, html: {class: 'form-horizontal' }) do |f| %>
  <%= f.input :name %>
  <div class="form-actions">
   <%= f.button :submit, :class => "btn btn-primary" %>
   <%= link_to "Cancel", jobs_path, :class => "btn" %>
   <div>
<% end %>

app/views/workstations/edit.html.erb
<h1>Editing workstation</h1>

<%= render 'form' %>

<%= link_to 'Show', @workstation %> |
<%= link_to 'Back', workstations_path %>

app/views/workstations/index.html.erb
<h1>Listing workstations</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @workstations.each do |workstation| %>
      <tr>
        <td><%= link_to 'Show', workstation %></td>
        <td><%= link_to 'Edit', edit_workstation_path(workstation) %></td>
        <td><%= link_to 'Destroy', workstation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workstation', new_workstation_path %>

app/views/workstations/new.html.erb
<h1>New workstation</h1>

<%= render 'form' %>

<%= link_to 'Back', workstations_path %>

app/views/workstations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_workstation_path(@workstation) %> |
<%= link_to 'Back', workstations_path %>